# ~/.config/starship.toml
# Inserts a blank line between shell prompts
add_newline = false

[username]
show_always = true

[directory]
truncate_to_repo = true
truncation_length = 3

[container]
disabled = true
